const root=document.documentElement,systemMotion=matchMedia('(prefers-reduced-motion: reduce)');
const theme=document.querySelector('.theme-toggle'),menu=document.querySelector('.menu-toggle'),nav=document.querySelector('nav'),motion=document.querySelector('.founder-motion');
let paused=false,queued=false;const reduced=()=>paused||systemMotion.matches;
function syncTheme(){const light=root.dataset.theme==='light';theme.setAttribute('aria-label',light?'Switch to dark mode':'Switch to light mode');theme.title=theme.getAttribute('aria-label');theme.querySelector('svg').innerHTML=light?'<path d="M20 14a8 8 0 0 1-10-10 8 8 0 1 0 10 10Z"/>':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>'}
theme.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';try{localStorage.setItem('vxl-theme',root.dataset.theme)}catch{}syncTheme()});syncTheme();
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu')}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();menu.focus()}});matchMedia('(min-width:641px)').addEventListener('change',e=>{if(e.matches)closeMenu()});
const animations=new Set();
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;observer.unobserve(e.target);if(reduced())continue;const a=e.target.animate([{opacity:0,transform:'translateY(24px)'},{opacity:1,transform:'translateY(0)'}],{duration:900,easing:'cubic-bezier(.2,.7,.2,1)'});animations.add(a);a.onfinish=()=>animations.delete(a)}},{threshold:.12});document.querySelectorAll('[data-enter]').forEach(n=>observer.observe(n));
const landscape=document.querySelector('.founder-landscape'),timeline=document.querySelector('.founder-timeline'),progress=document.querySelector('.reading-progress');
function updateScroll(){queued=false;const height=root.scrollHeight-innerHeight;progress.style.width=`${height>0?scrollY/height*100:0}%`;if(reduced())return;const b=landscape.getBoundingClientRect();if(b.bottom>0&&b.top<innerHeight){const p=Math.max(0,Math.min(1,(innerHeight-b.top)/(innerHeight+b.height)));landscape.style.setProperty('--landscape-shift',`${-8+p*6}%`)}const t=timeline.getBoundingClientRect();timeline.style.setProperty('--timeline-fill',`${Math.max(0,Math.min(100,(innerHeight*.65-t.top)/t.height*100))}%`)}
function schedule(){if(!queued){queued=true;requestAnimationFrame(updateScroll)}}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});
function applyMotion(){root.dataset.motion=reduced()?'off':'on';motion.setAttribute('aria-pressed',String(reduced()));motion.textContent=systemMotion.matches?'Reduced motion':paused?'Resume motion':'Pause motion';motion.disabled=systemMotion.matches;if(reduced()){animations.forEach(a=>a.finish());animations.clear()}schedule()}
motion.addEventListener('click',()=>{paused=!paused;applyMotion()});systemMotion.addEventListener('change',applyMotion);applyMotion();
